DELETE http://localhost:3001/api/applications/600758426a7424a9f7258ff7
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1heWFua2FwcCIsImlkIjoiNjAwNzU2YzM2YTc0MjRhOWY3MjU4ZmY2IiwiaWF0IjoxNjExMDk0MDAzfQ.NCFBz-BILhf1jLz63UfWGyzNySZOcPehu1IxzX3_mnE
